### ISSUE TITLE
Merge efforts with another httpie clone

### ISSUE THREAD

**Issue by andresv** [mark-burnett/ht#3]
It seems that https://github.com/ducaale/yahc has developed further however at the moment it is in an identity crisis. It doesn't have a good name and `ht` is already taken by this project. @mark-burnett what do you think if those 2 projects can be merged together, preferably forking https://github.com/ducaale/yahc as this is advanced further and using `ht` as a name for the combined effort.
Here is original ticket about this https://github.com/ducaale/yahc/issues/1.

**Comment by mark-burnett** [comment]
Name transfer is in progress!
